/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'blog-posts': BlogPost;
    'knowledge-base': KnowledgeBase;
    faqs: Faq;
    'pricing-plans': PricingPlan;
    solutions: Solution;
    'product-features': ProductFeature;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    changelog: Changelog;
    'navigation-menus': NavigationMenu;
    'form-submissions': FormSubmission;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'knowledge-base': KnowledgeBaseSelect<false> | KnowledgeBaseSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'product-features': ProductFeaturesSelect<false> | ProductFeaturesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    changelog: ChangelogSelect<false> | ChangelogSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  layout?: ('standard' | 'fullWidth' | 'landing') | null;
  status: 'draft' | 'published' | 'archived';
  publishedDate?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Brief summary for previews (max 200 characters)
   */
  excerpt: string;
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  category: 'product-updates' | 'company-news' | 'best-practices' | 'case-studies' | 'industry-insights';
  tags?: string[] | null;
  status: 'draft' | 'published' | 'archived';
  publishedDate: string;
  /**
   * Estimated reading time
   */
  readTime?: number | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base".
 */
export interface KnowledgeBase {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'getting-started' | 'features' | 'integrations' | 'troubleshooting' | 'best-practices' | 'advanced';
  subcategory?: string | null;
  relatedArticles?: (number | KnowledgeBase)[] | null;
  /**
   * Keywords to improve search discoverability
   */
  searchKeywords?: string[] | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Number of times this article was viewed
   */
  viewCount?: number | null;
  /**
   * Number of "helpful" votes
   */
  helpfulCount?: number | null;
  /**
   * Number of "not helpful" votes
   */
  notHelpfulCount?: number | null;
  /**
   * Last time content accuracy was verified
   */
  lastReviewed?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'technical' | 'billing' | 'account' | 'features' | 'security';
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  relatedArticles?: (number | KnowledgeBase)[] | null;
  helpfulCount?: number | null;
  notHelpfulCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  planName: string;
  planType: 'starter' | 'professional' | 'enterprise' | 'custom';
  /**
   * Brief plan description
   */
  description: string;
  price: number;
  billingPeriod: 'monthly' | 'annual';
  currency: 'USD' | 'EUR' | 'GBP';
  features: {
    feature: string;
    included?: boolean | null;
    /**
     * E.g., "Up to 5", "Unlimited", "10GB"
     */
    limit?: string | null;
    id?: string | null;
  }[];
  cta: {
    text: string;
    url: string;
    variant?: ('primary' | 'secondary' | 'outline') | null;
  };
  /**
   * Mark as "Most Popular" plan
   */
  popular?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  subtitle: string;
  heroImage?: (number | null) | Media;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  keyFeatures?:
    | {
        title: string;
        description: string;
        /**
         * Icon name from Tabler Icons (e.g., "IconRocket")
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  caseStudies?: (number | CaseStudy)[] | null;
  cta?: {
    text?: string | null;
    url?: string | null;
  };
  status: 'draft' | 'published' | 'archived';
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  companyName: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  companyLogo: number | Media;
  industry: 'saas' | 'ecommerce' | 'healthcare' | 'finance' | 'education' | 'manufacturing' | 'other';
  companySize: 'startup' | 'smb' | 'enterprise';
  challenge: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  solution: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  results: {
    /**
     * E.g., "Revenue Growth", "Time Saved"
     */
    metric: string;
    /**
     * E.g., "50%", "10 hours/week"
     */
    value: string;
    /**
     * Optional context, e.g., "vs. previous year"
     */
    improvement?: string | null;
    id?: string | null;
  }[];
  quote: {
    text: string;
    author: string;
    role: string;
    photo?: (number | null) | Media;
  };
  heroImage?: (number | null) | Media;
  status: 'draft' | 'published' | 'archived';
  publishedDate?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-features".
 */
export interface ProductFeature {
  id: number;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short catchy description (one sentence)
   */
  tagline: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Feature icon or illustration
   */
  icon?: (number | null) | Media;
  /**
   * Screenshot showing the feature
   */
  screenshot?: (number | null) | Media;
  /**
   * Demo video (optional)
   */
  video?: (number | null) | Media;
  category?: ('planning' | 'collaboration' | 'analytics' | 'automation' | 'integration' | 'visualization') | null;
  /**
   * Which plans include this feature
   */
  availableIn?: ('starter' | 'professional' | 'enterprise')[] | null;
  comingSoon?: boolean | null;
  order: number;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Keep it concise and impactful (max 500 characters)
   */
  quote: string;
  author: string;
  /**
   * E.g., "CEO", "Product Manager"
   */
  role: string;
  company: string;
  companyLogo?: (number | null) | Media;
  photo?: (number | null) | Media;
  /**
   * Rating out of 5
   */
  rating?: number | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog".
 */
export interface Changelog {
  id: number;
  /**
   * Semantic version (e.g., "1.2.0")
   */
  version: string;
  releaseDate: string;
  /**
   * Release title or theme
   */
  title: string;
  /**
   * Brief overview of this release
   */
  summary: string;
  changes: {
    type: 'feature' | 'improvement' | 'bugfix' | 'security' | 'documentation';
    description: string;
    id?: string | null;
  }[];
  /**
   * Does this release include breaking changes?
   */
  breaking?: boolean | null;
  /**
   * Describe the breaking changes and migration steps
   */
  breakingDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  /**
   * Internal name for this menu
   */
  name: string;
  location: 'header' | 'footer' | 'mobile';
  items: {
    label: string;
    type: 'custom' | 'page' | 'dropdown';
    url?: string | null;
    page?: (number | null) | Page;
    children?:
      | {
          label: string;
          url: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    openInNewTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formType: 'contact' | 'demo' | 'waitlist' | 'newsletter' | 'support';
  name?: string | null;
  email: string;
  company?: string | null;
  phone?: string | null;
  message?: string | null;
  /**
   * Additional form data (UTM params, referrer, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  status: 'new' | 'contacted' | 'converted' | 'spam';
  /**
   * UTM source or referrer
   */
  source?: string | null;
  /**
   * Internal notes about this submission
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'knowledge-base';
        value: number | KnowledgeBase;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'product-features';
        value: number | ProductFeature;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'changelog';
        value: number | Changelog;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  layout?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  category?: T;
  tags?: T;
  status?: T;
  publishedDate?: T;
  readTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base_select".
 */
export interface KnowledgeBaseSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  category?: T;
  subcategory?: T;
  relatedArticles?: T;
  searchKeywords?: T;
  status?: T;
  viewCount?: T;
  helpfulCount?: T;
  notHelpfulCount?: T;
  lastReviewed?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  relatedArticles?: T;
  helpfulCount?: T;
  notHelpfulCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  planName?: T;
  planType?: T;
  description?: T;
  price?: T;
  billingPeriod?: T;
  currency?: T;
  features?:
    | T
    | {
        feature?: T;
        included?: T;
        limit?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        text?: T;
        url?: T;
        variant?: T;
      };
  popular?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  heroImage?: T;
  overview?: T;
  keyFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  caseStudies?: T;
  cta?:
    | T
    | {
        text?: T;
        url?: T;
      };
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-features_select".
 */
export interface ProductFeaturesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  icon?: T;
  screenshot?: T;
  video?: T;
  category?: T;
  availableIn?: T;
  comingSoon?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  companyName?: T;
  slug?: T;
  companyLogo?: T;
  industry?: T;
  companySize?: T;
  challenge?: T;
  solution?: T;
  results?:
    | T
    | {
        metric?: T;
        value?: T;
        improvement?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        author?: T;
        role?: T;
        photo?: T;
      };
  heroImage?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  company?: T;
  companyLogo?: T;
  photo?: T;
  rating?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "changelog_select".
 */
export interface ChangelogSelect<T extends boolean = true> {
  version?: T;
  releaseDate?: T;
  title?: T;
  summary?: T;
  changes?:
    | T
    | {
        type?: T;
        description?: T;
        id?: T;
      };
  breaking?: T;
  breakingDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              description?: T;
              id?: T;
            };
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  message?: T;
  metadata?: T;
  submittedAt?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription: string;
  logo: number | Media;
  favicon: number | Media;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    github?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  analytics?: {
    /**
     * Google Analytics 4 Measurement ID
     */
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
    /**
     * For privacy-friendly analytics
     */
    plausibleDomain?: string | null;
  };
  contact: {
    email: string;
    supportEmail: string;
    salesEmail?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  maintenance?: {
    /**
     * Enable maintenance mode
     */
    enabled?: boolean | null;
    /**
     * Message to display during maintenance
     */
    message?: string | null;
    expectedEndTime?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        plausibleDomain?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        supportEmail?: T;
        salesEmail?: T;
        phone?: T;
        address?: T;
      };
  maintenance?:
    | T
    | {
        enabled?: T;
        message?: T;
        expectedEndTime?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}