/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'blog-posts': BlogPost;
    faqs: Faq;
    'pricing-plans': PricingPlan;
    solutions: Solution;
    'navigation-menus': NavigationMenu;
    'form-submissions': FormSubmission;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'marketing-home': MarketingHome;
    'product-overview-page': ProductOverviewPage;
    'product-planning-page': ProductPlanningPage;
    'product-reporting-page': ProductReportingPage;
    'product-visuals-page': ProductVisualsPage;
    'product-knowledgebase-page': ProductKnowledgebasePage;
    'pricing-page': PricingPage;
    'blog-page': BlogPage;
    'faqs-page': FaqsPage;
    'support-page': SupportPage;
    'knowledge-base-page': KnowledgeBasePage;
    'contact-page': ContactPage;
    'legal-page': LegalPage;
    footer: Footer;
    'site-metadata': SiteMetadatum;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'marketing-home': MarketingHomeSelect<false> | MarketingHomeSelect<true>;
    'product-overview-page': ProductOverviewPageSelect<false> | ProductOverviewPageSelect<true>;
    'product-planning-page': ProductPlanningPageSelect<false> | ProductPlanningPageSelect<true>;
    'product-reporting-page': ProductReportingPageSelect<false> | ProductReportingPageSelect<true>;
    'product-visuals-page': ProductVisualsPageSelect<false> | ProductVisualsPageSelect<true>;
    'product-knowledgebase-page': ProductKnowledgebasePageSelect<false> | ProductKnowledgebasePageSelect<true>;
    'pricing-page': PricingPageSelect<false> | PricingPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'faqs-page': FaqsPageSelect<false> | FaqsPageSelect<true>;
    'support-page': SupportPageSelect<false> | SupportPageSelect<true>;
    'knowledge-base-page': KnowledgeBasePageSelect<false> | KnowledgeBasePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'legal-page': LegalPageSelect<false> | LegalPageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-metadata': SiteMetadataSelect<false> | SiteMetadataSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  layout?: ('standard' | 'fullWidth' | 'landing') | null;
  status: 'draft' | 'published' | 'archived';
  publishedDate?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Brief summary for previews (max 200 characters)
   */
  excerpt: string;
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  category: 'product-updates' | 'company-news' | 'best-practices' | 'case-studies' | 'industry-insights';
  tags?: string[] | null;
  status: 'draft' | 'published' | 'archived';
  publishedDate: string;
  /**
   * Estimated reading time
   */
  readTime?: number | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'technical' | 'billing' | 'account' | 'features' | 'security';
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  helpfulCount?: number | null;
  notHelpfulCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  planName: string;
  planType: 'starter' | 'professional' | 'enterprise' | 'custom';
  /**
   * Brief plan description
   */
  description: string;
  price: number;
  billingPeriod: 'monthly' | 'annual';
  currency: 'USD' | 'EUR' | 'GBP';
  features: {
    feature: string;
    included?: boolean | null;
    /**
     * E.g., "Up to 5", "Unlimited", "10GB"
     */
    limit?: string | null;
    id?: string | null;
  }[];
  cta: {
    text: string;
    url: string;
    variant?: ('primary' | 'secondary' | 'outline') | null;
  };
  /**
   * Stripe Price ID for monthly billing (e.g. price_xxx). Leave blank for custom/enterprise contact-sales plans.
   */
  stripePriceIdMonthly?: string | null;
  /**
   * Stripe Price ID for annual billing (e.g. price_xxx). Leave blank for custom/enterprise contact-sales plans.
   */
  stripePriceIdAnnual?: string | null;
  /**
   * Mark as "Most Popular" plan
   */
  popular?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Large bold headline — e.g. "WHAT'S KILLING YOUR RANKINGS?"
   */
  heroHeadline?: string | null;
  /**
   * Word or phrase within the headline to highlight in purple — e.g. "YOUR RANKINGS?"
   */
  heroHeadlineAccent?: string | null;
  /**
   * Paragraph shown to the right of the headline
   */
  heroBody?: string | null;
  /**
   * Process steps shown below the headline (e.g. Enter URL → Agent Analyzes → …)
   */
  heroSteps?:
    | {
        label: string;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * The key challenges or frustrations this solution resolves for the audience
   */
  challenges?:
    | {
        title: string;
        description: string;
        /**
         * Icon name from Tabler Icons (e.g., "clock", "puzzle", "bolt")
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  keyFeatures?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  /**
   * Internal name for this menu
   */
  name: string;
  location: 'header' | 'footer' | 'mobile';
  items: {
    label: string;
    type: 'custom' | 'page' | 'dropdown';
    url?: string | null;
    page?: (number | null) | Page;
    children?:
      | {
          label: string;
          url: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    openInNewTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formType: 'contact' | 'demo' | 'waitlist' | 'newsletter' | 'support';
  name?: string | null;
  email: string;
  company?: string | null;
  phone?: string | null;
  message?: string | null;
  /**
   * Additional form data (UTM params, referrer, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  status: 'new' | 'contacted' | 'converted' | 'spam';
  /**
   * UTM source or referrer
   */
  source?: string | null;
  /**
   * Internal notes about this submission
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  layout?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  category?: T;
  tags?: T;
  status?: T;
  publishedDate?: T;
  readTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  helpfulCount?: T;
  notHelpfulCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  planName?: T;
  planType?: T;
  description?: T;
  price?: T;
  billingPeriod?: T;
  currency?: T;
  features?:
    | T
    | {
        feature?: T;
        included?: T;
        limit?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        text?: T;
        url?: T;
        variant?: T;
      };
  stripePriceIdMonthly?: T;
  stripePriceIdAnnual?: T;
  popular?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  slug?: T;
  heroHeadline?: T;
  heroHeadlineAccent?: T;
  heroBody?: T;
  heroSteps?:
    | T
    | {
        label?: T;
        active?: T;
        id?: T;
      };
  heroImage?: T;
  challenges?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  keyFeatures?:
    | T
    | {
        title?: T;
        id?: T;
      };
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        page?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              description?: T;
              id?: T;
            };
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  message?: T;
  metadata?: T;
  submittedAt?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-home".
 */
export interface MarketingHome {
  id: number;
  hero?: {
    eyebrow?: string | null;
    badge?: string | null;
    headline?: string | null;
    subtitle?: string | null;
    pillars?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    useCases?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    trustSignals?:
      | {
          /**
           * Tabler icon name without the "Icon" prefix, e.g. "Sparkles", "ChartBar", "Users"
           */
          icon?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    carouselSlides?:
      | {
          title?: string | null;
          description?: string | null;
          /**
           * Optional screenshot/image for this slide
           */
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  coreFeatures?: {
    kicker?: string | null;
    heading?: string | null;
    description?: string | null;
    features?:
      | {
          icon?: ('bulb' | 'target' | 'report') | null;
          title?: string | null;
          description?: string | null;
          capabilities?:
            | {
                label?: string | null;
                id?: string | null;
              }[]
            | null;
          visuals?:
            | {
                label?: string | null;
                /**
                 * Optional screenshot for this visual card
                 */
                image?: (number | null) | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  socialProof?: {
    heading?: string | null;
    subheading?: string | null;
    logosLabel?: string | null;
    customerLogos?:
      | {
          companyName: string;
          logo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    description?: string | null;
    emailPlaceholder?: string | null;
    buttonLabel?: string | null;
    note?: string | null;
  };
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-overview-page".
 */
export interface ProductOverviewPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  howItWorksHeading?: string | null;
  howItWorksSubheading?: string | null;
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  keyBenefits?: {
    heading?: string | null;
    subheading?: string | null;
    benefits?:
      | {
          icon?: ('clock' | 'palette' | 'adjustments' | 'books' | 'database' | 'sparkles') | null;
          title: string;
          description: string;
          pills?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  problemsHeading?: string | null;
  problemsSubheading?: string | null;
  problems?:
    | {
        problem: string;
        solution: string;
        id?: string | null;
      }[]
    | null;
  comparisonTable?: {
    heading?: string | null;
    subheading?: string | null;
    columns?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    rows?:
      | {
          aspect: string;
          values?:
            | {
                value: 'true' | 'false' | 'limited';
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-planning-page".
 */
export interface ProductPlanningPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  painPoints?:
    | {
        icon: 'spreadsheet' | 'timeline' | 'users' | 'puzzle' | 'clock' | 'chart';
        title: string;
        description: string;
        /**
         * RGB e.g. 124,58,237
         */
        color: string;
        id?: string | null;
      }[]
    | null;
  templates?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    /**
     * e.g. 8+
     */
    stat1Value?: string | null;
    stat1Label?: string | null;
    stat2Value?: string | null;
    stat2Label?: string | null;
    callout?: string | null;
    pills?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  metrics?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    pills?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    badgeLabel?: string | null;
    miniStat?: string | null;
  };
  tracking?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    views?:
      | {
          label: string;
          description: string;
          icon?: ('timeline' | 'columns' | 'route') | null;
          id?: string | null;
        }[]
      | null;
  };
  linkedPlanning?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  aiPlanning?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    steps?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    sourcePills?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reporting-page".
 */
export interface ProductReportingPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  painPoints?:
    | {
        icon: 'presentation' | 'chart' | 'target' | 'clock' | 'spreadsheet' | 'timeline';
        title: string;
        description: string;
        /**
         * RGB e.g. 124,58,237
         */
        color: string;
        id?: string | null;
      }[]
    | null;
  dashboards?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    metrics?:
      | {
          label: string;
          value: string;
          tone?: ('purple' | 'amber' | 'green') | null;
          id?: string | null;
        }[]
      | null;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  reportingOutputs?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    formats?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    templateRows?:
      | {
          label: string;
          /**
           * CSS width e.g. 88%
           */
          width: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-visuals-page".
 */
export interface ProductVisualsPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  painPoints?:
    | {
        icon: 'presentation' | 'moodsad' | 'chart' | 'dashboard' | 'spreadsheet' | 'timeline';
        title: string;
        description: string;
        /**
         * RGB e.g. 124,58,237
         */
        color: string;
        id?: string | null;
      }[]
    | null;
  infographics?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    capabilities?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  charting?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    capabilities?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  tables?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    capabilities?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    features?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  planViews?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    capabilities?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-knowledgebase-page".
 */
export interface ProductKnowledgebasePage {
  id: number;
  heroTitle?: string | null;
  /**
   * The portion of the title rendered in accent colour
   */
  heroAccent?: string | null;
  heroSubtitle?: string | null;
  capture?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    insightTags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    tagEtc?: string | null;
  };
  autoCapture?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    videoLabel?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  section3?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    points?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  aiQuery?: {
    kicker?: string | null;
    heading?: string | null;
    body?: string | null;
    qaExamples?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page".
 */
export interface PricingPage {
  id: number;
  /**
   * When checked, the pricing page shows a "Coming Soon" placeholder instead of live pricing. Uncheck to publish pricing.
   */
  comingSoon?: boolean | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * Label for the monthly billing toggle option
   */
  monthlyLabel?: string | null;
  /**
   * Label for the annual billing toggle option
   */
  annualLabel?: string | null;
  /**
   * Badge text shown next to the annual option
   */
  annualDiscountBadge?: string | null;
  /**
   * Shown in place of a price for enterprise/custom plans
   */
  customPriceLabel?: string | null;
  /**
   * Suffix appended to monthly price display
   */
  perMonthSuffix?: string | null;
  /**
   * Badge label on the highlighted plan
   */
  popularBadgeLabel?: string | null;
  /**
   * Note shown below price when annual billing is selected
   */
  billedAnnuallyLabel?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  readMoreLabel?: string | null;
  emptyStateHeading?: string | null;
  emptyStateMessage?: string | null;
  /**
   * Map blog category slugs to display labels.
   */
  categoryLabels?:
    | {
        /**
         * Category slug as stored on posts (e.g. "product-updates")
         */
        slug: string;
        /**
         * Display label shown in the UI (e.g. "Product Updates")
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs-page".
 */
export interface FaqsPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * Shown when there are no FAQs in the system
   */
  emptyStateMessage?: string | null;
  /**
   * Map category slugs to display labels. Order determines display sequence.
   */
  categoryLabels?:
    | {
        /**
         * Category slug as stored on FAQ records (e.g. "general")
         */
        slug: string;
        /**
         * Display label shown in the UI (e.g. "General")
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-page".
 */
export interface SupportPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  comingSoonMessage?: string | null;
  contactHeading?: string | null;
  /**
   * Support email address shown on the page
   */
  contactEmail?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base-page".
 */
export interface KnowledgeBasePage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  comingSoonHeading?: string | null;
  comingSoonMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  namePlaceholder?: string | null;
  emailPlaceholder?: string | null;
  companyPlaceholder?: string | null;
  messagePlaceholder?: string | null;
  submitButtonLabel?: string | null;
  successMessage?: string | null;
  responseNote?: string | null;
  seo?: {
    /**
     * Optimal length: 50-60 characters
     */
    metaTitle?: string | null;
    /**
     * Optimal length: 150-160 characters
     */
    metaDescription?: string | null;
    /**
     * Recommended: 1200x630px
     */
    ogImage?: (number | null) | Media;
    /**
     * Leave empty to use default URL
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Comma-separated keywords for SEO (e.g. business planning software, AI planning tool)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page".
 */
export interface LegalPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * Label for the Terms of Service tab
   */
  termsTabLabel?: string | null;
  /**
   * Label for the Privacy Policy tab
   */
  privacyTabLabel?: string | null;
  /**
   * Label for the Data Security tab
   */
  dataSecurityTabLabel?: string | null;
  /**
   * Full Terms of Service text
   */
  termsContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full Privacy Policy text
   */
  privacyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown when terms richText is empty
   */
  termsComingSoon?: string | null;
  /**
   * Shown when privacy richText is empty
   */
  privacyComingSoon?: string | null;
  /**
   * Full Data Security documentation text
   */
  dataSecurityContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown when data security richText is empty
   */
  dataSecurityComingSoon?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Name used in the copyright line (e.g. "Insaplan")
   */
  copyrightName?: string | null;
  /**
   * Text after the year and company name in the copyright line
   */
  copyrightSuffix?: string | null;
  linkGroups?:
    | {
        /**
         * Category heading (e.g. "Product")
         */
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-metadata".
 */
export interface SiteMetadatum {
  id: number;
  /**
   * Browser tab title for all marketing pages
   */
  defaultTitle?: string | null;
  /**
   * Default meta description
   */
  defaultDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  socialLinks?: {
    twitter?: string | null;
    linkedin?: string | null;
    github?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  analytics?: {
    /**
     * Google Analytics 4 Measurement ID
     */
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
    /**
     * For privacy-friendly analytics
     */
    plausibleDomain?: string | null;
  };
  contact?: {
    email?: string | null;
    supportEmail?: string | null;
    salesEmail?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  maintenance?: {
    /**
     * Enable maintenance mode
     */
    enabled?: boolean | null;
    /**
     * Message to display during maintenance
     */
    message?: string | null;
    expectedEndTime?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-home_select".
 */
export interface MarketingHomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        badge?: T;
        headline?: T;
        subtitle?: T;
        pillars?:
          | T
          | {
              label?: T;
              id?: T;
            };
        useCases?:
          | T
          | {
              label?: T;
              id?: T;
            };
        trustSignals?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        carouselSlides?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  coreFeatures?:
    | T
    | {
        kicker?: T;
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              capabilities?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              visuals?:
                | T
                | {
                    label?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  socialProof?:
    | T
    | {
        heading?: T;
        subheading?: T;
        logosLabel?: T;
        customerLogos?:
          | T
          | {
              companyName?: T;
              logo?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        emailPlaceholder?: T;
        buttonLabel?: T;
        note?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-overview-page_select".
 */
export interface ProductOverviewPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  howItWorksHeading?: T;
  howItWorksSubheading?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  keyBenefits?:
    | T
    | {
        heading?: T;
        subheading?: T;
        benefits?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              pills?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  problemsHeading?: T;
  problemsSubheading?: T;
  problems?:
    | T
    | {
        problem?: T;
        solution?: T;
        id?: T;
      };
  comparisonTable?:
    | T
    | {
        heading?: T;
        subheading?: T;
        columns?:
          | T
          | {
              label?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              aspect?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-planning-page_select".
 */
export interface ProductPlanningPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  painPoints?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  templates?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        stat1Value?: T;
        stat1Label?: T;
        stat2Value?: T;
        stat2Label?: T;
        callout?: T;
        pills?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  metrics?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
        pills?:
          | T
          | {
              label?: T;
              id?: T;
            };
        badgeLabel?: T;
        miniStat?: T;
      };
  tracking?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        views?:
          | T
          | {
              label?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  linkedPlanning?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  aiPlanning?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        steps?:
          | T
          | {
              label?: T;
              id?: T;
            };
        sourcePills?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reporting-page_select".
 */
export interface ProductReportingPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  painPoints?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  dashboards?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
        metrics?:
          | T
          | {
              label?: T;
              value?: T;
              tone?: T;
              id?: T;
            };
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  reportingOutputs?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
        formats?:
          | T
          | {
              label?: T;
              id?: T;
            };
        templateRows?:
          | T
          | {
              label?: T;
              width?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-visuals-page_select".
 */
export interface ProductVisualsPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  painPoints?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  infographics?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        capabilities?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  charting?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        capabilities?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  tables?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        capabilities?:
          | T
          | {
              label?: T;
              id?: T;
            };
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  planViews?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        capabilities?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-knowledgebase-page_select".
 */
export interface ProductKnowledgebasePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroAccent?: T;
  heroSubtitle?: T;
  capture?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        insightTags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        tagEtc?: T;
      };
  autoCapture?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        videoLabel?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  section3?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  aiQuery?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        qaExamples?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page_select".
 */
export interface PricingPageSelect<T extends boolean = true> {
  comingSoon?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  monthlyLabel?: T;
  annualLabel?: T;
  annualDiscountBadge?: T;
  customPriceLabel?: T;
  perMonthSuffix?: T;
  popularBadgeLabel?: T;
  billedAnnuallyLabel?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  readMoreLabel?: T;
  emptyStateHeading?: T;
  emptyStateMessage?: T;
  categoryLabels?:
    | T
    | {
        slug?: T;
        label?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs-page_select".
 */
export interface FaqsPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  emptyStateMessage?: T;
  categoryLabels?:
    | T
    | {
        slug?: T;
        label?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-page_select".
 */
export interface SupportPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  comingSoonMessage?: T;
  contactHeading?: T;
  contactEmail?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base-page_select".
 */
export interface KnowledgeBasePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  comingSoonHeading?: T;
  comingSoonMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  namePlaceholder?: T;
  emailPlaceholder?: T;
  companyPlaceholder?: T;
  messagePlaceholder?: T;
  submitButtonLabel?: T;
  successMessage?: T;
  responseNote?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page_select".
 */
export interface LegalPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  termsTabLabel?: T;
  privacyTabLabel?: T;
  dataSecurityTabLabel?: T;
  termsContent?: T;
  privacyContent?: T;
  termsComingSoon?: T;
  privacyComingSoon?: T;
  dataSecurityContent?: T;
  dataSecurityComingSoon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightName?: T;
  copyrightSuffix?: T;
  linkGroups?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-metadata_select".
 */
export interface SiteMetadataSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
        plausibleDomain?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        supportEmail?: T;
        salesEmail?: T;
        phone?: T;
        address?: T;
      };
  maintenance?:
    | T
    | {
        enabled?: T;
        message?: T;
        expectedEndTime?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}