# Digital Ocean App Platform configuration
name: insaplan-cms
region: nyc

services:
    - name: payload-cms
      github:
          repo: your-org/insaplan
          branch: main
          deploy_on_push: true
      source_dir: /payload-cms
      build_command: pnpm install && pnpm build
      run_command: pnpm start

      envs:
          - key: DATABASE_URL
            scope: RUN_AND_BUILD_TIME
            value: ${payload-db.DATABASE_URL}

          - key: PAYLOAD_SECRET
            scope: RUN_AND_BUILD_TIME
            type: SECRET

          - key: PAYLOAD_PUBLIC_SERVER_URL
            scope: RUN_AND_BUILD_TIME
            value: ${APP_URL}

          - key: REBUILD_WEBHOOK_URL
            scope: RUN_AND_BUILD_TIME
            type: SECRET

          - key: NODE_ENV
            scope: RUN_AND_BUILD_TIME
            value: production

      http_port: 3001

      instance_count: 1
      instance_size_slug: basic-xs

      routes:
          - path: /

databases:
    - name: payload-db
      engine: PG
      version: '15'
      production: true
      cluster_name: insaplan-db-cluster
