DROP TABLE "users_sessions" CASCADE;
  DROP TABLE "users" CASCADE;
  DROP TABLE "pages" CASCADE;
  DROP TABLE "pages_texts" CASCADE;
  DROP TABLE "_pages_v" CASCADE;
  DROP TABLE "_pages_v_texts" CASCADE;
  DROP TABLE "blog_posts" CASCADE;
  DROP TABLE "blog_posts_texts" CASCADE;
  DROP TABLE "_blog_posts_v" CASCADE;
  DROP TABLE "_blog_posts_v_texts" CASCADE;
  DROP TABLE "knowledge_base" CASCADE;
  DROP TABLE "knowledge_base_texts" CASCADE;
  DROP TABLE "knowledge_base_rels" CASCADE;
  DROP TABLE "_knowledge_base_v" CASCADE;
  DROP TABLE "_knowledge_base_v_texts" CASCADE;
  DROP TABLE "_knowledge_base_v_rels" CASCADE;
  DROP TABLE "faqs" CASCADE;
  DROP TABLE "faqs_rels" CASCADE;
  DROP TABLE "pricing_plans_features" CASCADE;
  DROP TABLE "pricing_plans" CASCADE;
  DROP TABLE "solutions_key_features" CASCADE;
  DROP TABLE "solutions_use_cases" CASCADE;
  DROP TABLE "solutions" CASCADE;
  DROP TABLE "solutions_texts" CASCADE;
  DROP TABLE "solutions_rels" CASCADE;
  DROP TABLE "_solutions_v_version_key_features" CASCADE;
  DROP TABLE "_solutions_v_version_use_cases" CASCADE;
  DROP TABLE "_solutions_v" CASCADE;
  DROP TABLE "_solutions_v_texts" CASCADE;
  DROP TABLE "_solutions_v_rels" CASCADE;
  DROP TABLE "product_features_available_in" CASCADE;
  DROP TABLE "product_features" CASCADE;
  DROP TABLE "_product_features_v_version_available_in" CASCADE;
  DROP TABLE "_product_features_v" CASCADE;
  DROP TABLE "case_studies_results" CASCADE;
  DROP TABLE "case_studies" CASCADE;
  DROP TABLE "case_studies_texts" CASCADE;
  DROP TABLE "_case_studies_v_version_results" CASCADE;
  DROP TABLE "_case_studies_v" CASCADE;
  DROP TABLE "_case_studies_v_texts" CASCADE;
  DROP TABLE "testimonials" CASCADE;
  DROP TABLE "changelog_changes" CASCADE;
  DROP TABLE "changelog" CASCADE;
  DROP TABLE "navigation_menus_items_children" CASCADE;
  DROP TABLE "navigation_menus_items" CASCADE;
  DROP TABLE "navigation_menus" CASCADE;
  DROP TABLE "form_submissions" CASCADE;
  DROP TABLE "media" CASCADE;
  DROP TABLE "payload_kv" CASCADE;
  DROP TABLE "payload_locked_documents" CASCADE;
  DROP TABLE "payload_locked_documents_rels" CASCADE;
  DROP TABLE "payload_preferences" CASCADE;
  DROP TABLE "payload_preferences_rels" CASCADE;
  DROP TABLE "payload_migrations" CASCADE;
  DROP TABLE "site_settings" CASCADE;
  DROP TYPE "public"."enum_users_role";
  DROP TYPE "public"."enum_pages_layout";
  DROP TYPE "public"."enum_pages_status";
  DROP TYPE "public"."enum__pages_v_version_layout";
  DROP TYPE "public"."enum__pages_v_version_status";
  DROP TYPE "public"."enum_blog_posts_category";
  DROP TYPE "public"."enum_blog_posts_status";
  DROP TYPE "public"."enum__blog_posts_v_version_category";
  DROP TYPE "public"."enum__blog_posts_v_version_status";
  DROP TYPE "public"."enum_knowledge_base_category";
  DROP TYPE "public"."enum_knowledge_base_status";
  DROP TYPE "public"."enum__knowledge_base_v_version_category";
  DROP TYPE "public"."enum__knowledge_base_v_version_status";
  DROP TYPE "public"."enum_faqs_category";
  DROP TYPE "public"."enum_pricing_plans_plan_type";
  DROP TYPE "public"."enum_pricing_plans_billing_period";
  DROP TYPE "public"."enum_pricing_plans_currency";
  DROP TYPE "public"."enum_pricing_plans_cta_variant";
  DROP TYPE "public"."enum_solutions_status";
  DROP TYPE "public"."enum__solutions_v_version_status";
  DROP TYPE "public"."enum_product_features_available_in";
  DROP TYPE "public"."enum_product_features_category";
  DROP TYPE "public"."enum_product_features_status";
  DROP TYPE "public"."enum__product_features_v_version_available_in";
  DROP TYPE "public"."enum__product_features_v_version_category";
  DROP TYPE "public"."enum__product_features_v_version_status";
  DROP TYPE "public"."enum_case_studies_industry";
  DROP TYPE "public"."enum_case_studies_company_size";
  DROP TYPE "public"."enum_case_studies_status";
  DROP TYPE "public"."enum__case_studies_v_version_industry";
  DROP TYPE "public"."enum__case_studies_v_version_company_size";
  DROP TYPE "public"."enum__case_studies_v_version_status";
  DROP TYPE "public"."enum_changelog_changes_type";
  DROP TYPE "public"."enum_navigation_menus_items_type";
  DROP TYPE "public"."enum_navigation_menus_location";
  DROP TYPE "public"."enum_form_submissions_form_type";
  DROP TYPE "public"."enum_form_submissions_status";
